GitHubRepo/Controllers/RepoController.cs
using GitHubRepo.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace GitHubRepo.Controllers
{
    public class RepoController : Controller
    {

        List<Repo> repoList = new List<Repo>();
        public IActionResult SaveBM(string Name)
        {

            //save this repo (by id to session)
            List<Repo> repoList = HttpContext.Session.GetComplexData<List<Repo>>("repoList");
            List<Repo> repoListBM = HttpContext.Session.GetComplexData<List<Repo>>("repoListBM");

            int repNum = Int32.Parse(Name);
            //bool has = repoList.Any(rep => rep.RepoId == Int32.Parse(Name));

            //var addressList = addr.Where(item => ids.Contains(item.Id)).Select(a => a).ToList();

            // var newlist = repoList.Where(item => repoList.Contains(item.RepoId==55)).Select(a => a).ToList();
            Repo repoItem = repoList.FirstOrDefault(itm => itm.RepoId == repNum);
            if (repoItem != null)
            {
                //check also that item is not already bookmarked
                if(repoListBM.FirstOrDefault(itm => itm.RepoId == repNum)==null)
                {
                    repoListBM.Add(repoItem);
                    HttpContext.Session.SetComplexData("repoListBM", repoListBM);
                }
            }


            return new EmptyResult();
        }

            //  /Repo/GitHubResult/{searchPhrase}
            [Route("Repo/GitHubResult/{searchPhrase?}")]
        public async Task<IActionResult> GitHubResult(string searchPhrase)
        {
            List<Item> repoOrigList = new List<Item>();
          
           

            using (var httpClient = new HttpClient())
            {
                //
               // User - Agent: Mozilla / 5.0(Windows NT 10.0; Win64; x64) AppleWebKit / 537.36(KHTML, like Gecko) Chrome / 87.0.4280.88 Safari / 537.36
                httpClient.DefaultRequestHeaders.UserAgent.ParseAdd("Mozilla/5.0 (compatible; AcmeInc/1.0)");
                using (var response = await httpClient.GetAsync("https://api.github.com/search/repositories?q=" + searchPhrase))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();

                    // jsonObject ourlisting = JsonConvert.DeserializeObject<jsonObject>(strJSON);
                    Rootobject ourlisting = JsonConvert.DeserializeObject<Rootobject>(apiResponse);
                    repoOrigList =  ourlisting.items.ToList();


                    foreach (var item in repoOrigList)
                    {
                        Repo rep = new Repo();
                        rep.RepoId = item.id;
                        rep.RepoName = item.name;
                        rep.AvatarURL = item.owner.avatar_url;
                        rep.IsBookMarked = false;

                        repoList.Add(rep);

                        //var id = item.
                    }

                    //save repoList to Session
                    HttpContext.Session.SetComplexData("repoList", repoList);
                    //repoListBMs only need to be initiated  once!
                    if (HttpContext.Session.GetComplexData<List<Repo>>("repoListBM") == null)
                    {
                        HttpContext.Session.SetComplexData("repoListBM", new List<Item>());
                    }

                }
            }

            return View(repoList);
        }

        public IActionResult GetResult(string searchPhrase)
        {
            //LoggedUserVM user = GetUserDataById(model.userId);
            //rech out ti github and get api


            //Create Session with complex object   
            HttpContext.Session.SetComplexData("loggerUser", "user");

            return Json("");  //LIST OF RESULT          _   gitHubRepository.List()

        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

GitHubRepo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GitHubRepo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GitHubRepo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Results">Repo Search Results</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="BookMarks">BookMark Repos</a>
                        </li>
                    </ul>

                </div>
                <form class="form-inline my-2 my-lg-0" asp-action="GitHubResult" asp-controller="Repo" method="post">
                    <input class="txtSearch form-control mr-sm-2" type="text" name="searchPhrase" style="width:250px" placeholder="Search GitHub Repository">
                    <button class="btn btnSearch  btn-secondary my-2 my-sm-0" type="submit" on>Search</button>
                </form>


            </div>z
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - GitHubRepo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>


   
        <script>
            $(document).ready(function () {

                $("form").submit(function () {
                    if ($('.txtSearch').val() == "" || $('.txtSearch').val().length < 3) {
                        alert('Please enter search text of at least 3 chars');
                        return false;
                    }

                    else if ($('.txtSearch').val().length > 20) 
                    {
                        alert('Please enter search text of max 20 chars');
                        return false;
                    }
                });
            });

        </script>
 

    @RenderSection("Scripts", required: false)
</body>
</html>